seed: 42
dataset: 'Receipt'
activity_num: 24
avg_len: 12


k_fold_num: 3

model_parameters:
  model_name: 'SGAP'
  batch_size: 64
  num_epochs: 2 
  encoder_type: lstm # transformer
  layer_num: 2
  hidden_size: 8 
  feature_num: 32 
  dropout: 0.4
  learning_rate: 0.001
  encoder_layer: 1
  num_head: 2        